#!/usr/bin/env nextflow

/*
 * CAR T Cell Exhaustion Transcriptomics Pipeline
 * ----------------------------------------------
 * This pipeline processes RNA-seq data to map gene expression changes 
 * across unactivated, acutely activated, and exhausted states.
 */

// Define default pipeline parameters
params.reads = "$projectDir/data/*_{1,2}.fastq.gz"
params.outdir = "results"
// Standard GRCh38 Reference Parameters
params.fasta = "$projectDir/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
params.gtf   = "$projectDir/reference/Homo_sapiens.GRCh38.110.gtf"

//--- PROCESS DEFINITIONS ---
 process FASTQC{
    // Labels the terminal output so you know exactly which sample is running
    tag "QC on $sample_id"

    // Copies the final output files out of the hidden work directory nd into your result folder
    publishDir "${params.outdir}/fastqc", mode: 'copy'

    // Pull the official Biocontainer for FastQC from the Quay.io registr
    container "quay.io/biocontainers/fastqc:0.12.1--hdfd78af_0"

    input:
    // Matches the [ sample_id,[read1, read2] ] structure generated by fromFilePairs
    tuple val(sample_id), path(reads)

    output:
    // Captures both the HTML visual reports and the raw zip data
    path "*.{html,zip}"

    script:
    """
    // The actual command line execution. -q runs it quietly to avoid terminal spam.
    fastqc -q ${reads}
    """
 }

workflow {
    // Create a channel that pairs forward (_1) and reverse (_2) sequencing reads together
    read_pairs_ch = channel.fromFilePairs(params.reads)
    
    // Output the matched pairs to the terminal to verify the channel works
    read_pairs_ch.view()
}